### ISSUE TITLE
Add SuperFast connectors as an extension.

### ISSUE THREAD

**Issue by ctessum** [EarthSciML/AtmosphericDeposition.jl#22]
Julia has a feature called "extensions" where we can have code that is only available when two packages are loaded at the same time. This will allow us to have code that connects the wet and dry deposition code to SuperFast without always having to load the GasChem Package. The documentation is here: https://docs.julialang.org/en/v1/manual/code-loading/#man-extensions

Basically, the idea is that we can create a file named `/ext/GasChemExt.jl` (*not* `/src/ext/GasChemExt.jl`) in this repository, then in that file put:

``` julia
module GasChemExt

... connector code from here: https://github.com/jialinl6/box_model/blob/c65a56a328d865c119f2148efabb9d72bc5641b7/s_f_d.jl#L6

end
```

The, in `Project.toml` we can add: 

``` toml
[weakdeps]
GasChem = "58070593-4751-4c87-a5d1-63807d11d76c"

[extensions]
GasChemExt = "GasChem"
```

(Also add tests and documentation)
